---
abstract: "Check the compiler's availability"
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF@ GMAIL COM>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-CheckCompiler
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Devel::AssertC99:
    file: lib/Devel/AssertC99.pm
  Devel::CheckCompiler:
    file: lib/Devel/CheckCompiler.pm
    version: 0.05
requires:
  Exporter: 0
  ExtUtils::CBuilder: 0
  File::Temp: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Devel-CheckCompiler/issues
  homepage: https://github.com/tokuhirom/Devel-CheckCompiler
  repository: git://github.com/tokuhirom/Devel-CheckCompiler.git
version: 0.05
x_contributors:
  - 'Neil Bowers <neil@bowers.com>'
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
  - 'Syohei YOSHIDA <syohex@gmail.com>'
