---
abstract: "boost Cookie::Baker's crush_cookie"
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cookie-Baker-XS
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Cookie::Baker::XS:
    file: lib/Cookie/Baker/XS.pm
    version: 0.03
requires:
  Exporter: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/kazeburo/Cookie-Baker-XS/issues
  homepage: https://github.com/kazeburo/Cookie-Baker-XS
  repository: git://github.com/kazeburo/Cookie-Baker-XS.git
version: 0.03
