---
abstract: 'A module that allows you to declare real exception classes in Perl'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Test::More: 0.88
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exception-Class
requires:
  Class::Data::Inheritable: 0.02
  Devel::StackTrace: 1.20
  Scalar::Util: 0
  base: 0
  overload: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Bits
  homepage: http://metacpan.org/release/Test-Bits
  repository: git://git.urth.org/Test-Bits.git
version: 1.38
x_authority: cpan:DROLSKY
x_contributors:
  - 'Ricardo Signes <rjbs@cpan.org>'
  - 'autarch <devnull@localhost>'
  - 'convert-repo <devnull@localhost>'
  - 'unknown <devnull@localhost>'
