---
abstract: 'Get information about a class and its structure'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Class::Inspector
name: Class-Inspector
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Spec: 0.80
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Class-Inspector
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Class-Inspector
version: 1.28
