---
abstract: 'Build.PL install path logic made easy'
author:
  - 'Ken Williams <kwilliams@cpan.org>'
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ExtUtils-InstallPaths
provides:
  ExtUtils::InstallPaths:
    file: lib/ExtUtils/InstallPaths.pm
    version: 0.010
requires:
  Carp: 0
  ExtUtils::Config: 0.002
  File::Spec: 0
  perl: 5.008001
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=ExtUtils-InstallPaths
  repository: git://github.com/Leont/extutils-installpaths.git
version: 0.010
