---
abstract: 'Parse cpanfile'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Module-CPANfile
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
recommends:
  Pod::Usage: '0'
requires:
  CPAN::Meta: '2.12091'
  CPAN::Meta::Prereqs: '2.12091'
  parent: '0'
resources:
  bugtracker: https://github.com/miyagawa/cpanfile/issues
  homepage: https://github.com/miyagawa/cpanfile
  repository: https://github.com/miyagawa/cpanfile.git
version: '1.1000'
x_contributors:
  - 'Atsushi Kato <ktat@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Gregory Oschwald <oschwald@gmail.com>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
  - 'Masahiro Honma <hiratara@cpan.org>'
  - 'Michiel Beijen <michiel.beijen@gmail.com>'
  - 'grtodd <gtodd@iciti.ca>'
  - 'ikasam_a <masaki.nakagawa@gmail.com>'
