---
abstract: 'Only use Sub::Exporter if you need it'
author:
  - 'frew - Arthur Axel Schmidt (cpan:FREW) <frioux+cpan@gmail.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.8, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sub-Exporter-Progressive
no_index:
  directory:
    - t
    - inc
requires: {}
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Sub-Exporter-Progressive
  homepage: http://search.cpan.org/dist/Sub-Exporter-Progressive/
  repository: git://git.shadowcat.co.uk/p5sagit/Sub-Exporter-Progressive.git
version: 0.001011
