---
abstract: 'Store multiple values per key'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hash-MultiValue
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  perl: 5.008001
resources:
  bugtracker: https://github.com/miyagawa/Hash-MultiValue/issues
  homepage: https://github.com/miyagawa/Hash-MultiValue
  repository: https://github.com/miyagawa/Hash-MultiValue.git
version: 0.15
x_contributors:
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Hans Dieter Pearcey <hdp@weftsoar.net>'
  - 'Peter Rabbitson <ribasushi@cpan.org>'
  - 'Tatsuhiko Miyagawa <miyagawa@gmail.com>'
  - 'chansen <chansen@cpan.org>'
