---
abstract: 'Supports app to run as a reverse proxy backend'
author:
  - 'This module is originally written by Kazuhiro Osawa as L<HTTP::Engine::Middleware::ReverseProxy> for L<HTTP::Engine>.'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Middleware-ReverseProxy
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Plack: 0.9988
  Plack::Middleware: 0
  Plack::Request: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/lopnor/Plack-Middleware-ReverseProxy.git
version: 0.15
