---
abstract: 'XS implementation of parser and builder for application/x-www-form-urlencoded'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  JSON: 2
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Form-UrlEncoded-XS
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WWW::Form::UrlEncoded::XS:
    file: lib/WWW/Form/UrlEncoded/XS.pm
    version: 0.19
requires:
  Exporter: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/kazeburo/WWW-Form-UrlEncoded-XS/issues
  homepage: https://github.com/kazeburo/WWW-Form-UrlEncoded-XS
  repository: git://github.com/kazeburo/WWW-Form-UrlEncoded-XS.git
version: 0.19
