--- #YAML:1.0
name:               LWP-MediaTypes
version:            6.02
abstract:           guess media type for a file or a URL
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006002
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/gisle/lwp-mediatypes
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
