---
abstract: 'High-performance preforking PSGI/Plack web server'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  LWP::UserAgent: '0'
  Test::More: '0'
  Test::Requires: '0'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Starman
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Data::Dump: '0'
  HTTP::Date: '0'
  HTTP::Parser::XS: '0'
  HTTP::Status: '0'
  Net::Server: '2.007'
  Plack: '0.9971'
  Test::TCP: '2.00'
  parent: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/Starman/issues
  homepage: https://github.com/miyagawa/Starman
  repository: https://github.com/miyagawa/Starman.git
version: '0.4010'
x_contributors:
  - 'Adam Guthrie <adam.guthrie@dvlgames.com>'
  - 'Alex Vandiver <alex@chmrr.net>'
  - 'Aristotle Pagaltzis <pagaltzis@gmx.de>'
  - 'Audrey Tang <audreyt@audreyt.org>'
  - 'Chia-liang Kao <clkao@clkao.org>'
  - 'David Steinbrunner <dsteinbrunner@pobox.com>'
  - 'Graham Barr <gbarr@pobox.com>'
  - 'Grant McLean <grant@catalyst.net.nz>'
  - 'Gregory Oschwald <goschwald@maxmind.com>'
  - 'John Siracusa <siracusa@gmail.com>'
  - 'Leon Brocard <acme@astray.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
  - 'Paulo E. Castro <pauloedgarcastro@gmail.com>'
  - 'Perlover <perlover@perlover.com>'
  - 'Peter Makholm <peter@makholm.net>'
  - 'Piotr Roszatycki <piotr.roszatycki@gmail.com>'
  - 'Slobodan Mišković <slobodan@miskovic.ca>'
  - 'cho45 <cho45@lowreal.net>'
  - 'spleenjack <spleenjack@gmail.com>'
