---
abstract: 'GNU C library compatible strftime for loggers and servers'
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: POSIX-strftime-Compiler
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  POSIX::strftime::Compiler:
    file: lib/POSIX/strftime/Compiler.pm
    version: '0.40'
requires:
  Carp: '0'
  Exporter: '0'
  POSIX: '0'
  Time::Local: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/kazeburo/POSIX-strftime-Compiler/issues
  homepage: https://github.com/kazeburo/POSIX-strftime-Compiler
  repository: git://github.com/kazeburo/POSIX-strftime-Compiler.git
version: '0.40'
x_contributors:
  - 'Piotr Roszatycki <piotr.roszatycki@gmail.com>'
