--- #YAML:1.0
name:               List-MoreUtils
version:            0.33
abstract:           Provide the stuff missing in List::Util
author:
    - Tassilo von Parseval <tassilo.von.parseval@rwth-aachen.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::CBuilder:   0.27
    ExtUtils::MakeMaker:  6.52
build_requires:
    Test::More:  0.42
requires:
    perl:        5.00503
    Test::More:  0.82
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
