--- #YAML:1.0
name:               Encode-Locale
version:            1.03
abstract:           Determine the locale encoding
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test:  0
requires:
    Encode:         2
    Encode::Alias:  0
    perl:           5.008
resources:
    repository:  http://github.com/gisle/encode-locale
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    I18N::Langinfo:  0
    Win32::Console:  0
