--- #YAML:1.0
name:               HTTP-Message
version:            6.06
abstract:           HTTP style messages
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::Raw::Zlib:  0
    Encode:               2.21
    Encode::Locale:       1
    HTTP::Date:           6
    IO::Compress::Bzip2:  2.021
    IO::Compress::Deflate:  0
    IO::Compress::Gzip:   0
    IO::HTML:             0
    IO::Uncompress::Bunzip2:  2.021
    IO::Uncompress::Gunzip:  0
    IO::Uncompress::Inflate:  0
    IO::Uncompress::RawInflate:  0
    LWP::MediaTypes:      6
    MIME::Base64:         2.1
    MIME::QuotedPrint:    0
    perl:                 5.008001
    URI:                  1.10
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/libwww-perl/http-message
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
